# CrazyAuctionAddon 設定ファイル
# このファイルはプラグイン初回起動時にコピーされます
blocked-names:
  - "禁止aaaaaaaaaaaaaaaaaaaaaaaaaaa"         # アイテム名に「禁止aaaaaaaaaaaaaaaaaaaaaaaaaaa」が含まれる場合ブロック
  - "ダメ絶対世界最強ウルトラメガソード異世界バージョンアンドメガマックスEX"       # 複数指定可能
blocked-lores:
  - "絶対絶対取引しちゃだめだよaaaaaaaaaaaaaaaaaaaa"
  - "取引禁止"